language: julia
os:
  - osx
  - linux
julia:
  - 0.6
notifications:
  email: false
addons:
  apt:
    packages:
    - hdf5-tools
before_script:
    - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; brew link --overwrite gcc; brew install hdf5; fi
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'Pkg.clone(pwd());'
# #  - julia -e 'ENV["FEHM_NO_PYTHON"]=""; ENV["FEHM_NO_PLOT"]=""; Pkg.build("FEHM"); Pkg.test("FEHM"; coverage=true)'
#   - julia -e 'ENV["FEHM_TRAVIS"]=""; Pkg.build("FEHM"); Pkg.test("FEHM"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("FEHM")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
